In [3]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [4]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
data = pd.read_csv('engine_data.csv')

In [6]:
data.head()

Engine rpm  Lub oil pressure  Fuel pressure  Coolant pressure  \
0         700          2.493592      11.790927          3.178981   
1         876          2.941606      16.193866          2.464504   
2         520          2.961746       6.553147          1.064347   
3         473          3.707835      19.510172          3.727455   
4         619          5.672919      15.738871          2.052251   

   lub oil temp  Coolant temp  Engine Condition  
0     84.144163     81.632187                 1  
1     77.640934     82.445724                 0  
2     77.752266     79.645777                 1  
3     74.129907     71.774629                 1  
4     78.396989     87.000225                 0

In [7]:
X = data.iloc[:,:-1]
X.head()

Engine rpm  Lub oil pressure  Fuel pressure  Coolant pressure  \
0         700          2.493592      11.790927          3.178981   
1         876          2.941606      16.193866          2.464504   
2         520          2.961746       6.553147          1.064347   
3         473          3.707835      19.510172          3.727455   
4         619          5.672919      15.738871          2.052251   

   lub oil temp  Coolant temp  
0     84.144163     81.632187  
1     77.640934     82.445724  
2     77.752266     79.645777  
3     74.129907     71.774629  
4     78.396989     87.000225

In [8]:
Y = data.iloc[:,-1] 
Y.head()

0    1
1    0
2    1
3    1
4    0
Name: Engine Condition, dtype: int64

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [10]:
model_logistic = LogisticRegression()

In [11]:
model_logistic.fit(X_train, Y_train)

C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
Y_pred = model_logistic.predict(X_test)

In [57]:
file_name='Trained Model/LR_model.sav'
joblib.dump(model_logistic,file_name)

['Trained Model/LR_model.sav']

In [14]:
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6529602456918615


In [15]:
print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.28      0.38      2214
           1       0.67      0.88      0.76      3647

    accuracy                           0.65      5861
   macro avg       0.63      0.58      0.57      5861
weighted avg       0.64      0.65      0.62      5861



In [16]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, Y_pred))


Confusion Matrix:
[[ 619 1595]
 [ 439 3208]]


In [18]:
pip install xgboost

  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/24/ec/ad387100fa3cc2b9b81af0829b5ecfe75ec5bb19dd7c19d4fea06fb81802/xgboost-2.0.3-py3-none-win_amd64.whl.metadata
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/99.8 MB 1.3 MB/s eta 0:01:16
   ---------------------------------------- 0.2/99.8 MB 1.1 MB/s eta 0:01:27
   ---------------------------------------- 0.3/99.8 MB 1.5 MB/s eta 0:01:05
   ---------------------------------------- 0.4/99.8 MB 1.6 MB/s eta 0:01:01
   ---------------------------------------- 0.5/99.8 MB 1.8 MB/s eta 0:00:56
   ---------------------------------------- 0.6/99.8 MB 1.9 MB/s eta 0:00:52
   ---------------------------------------- 0.6/99.8 MB 1.9 MB/s eta 0:00:52
   ---------------------------------------- 0.6/99.8 MB 1.9 MB/s eta 0:00:52
   ------------------------------------

In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [20]:
model_xgboost = XGBClassifier()

In [21]:
model_xgboost.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [22]:
Y_pred = model_xgboost.predict(X_test)

In [56]:
file_name='Trained Model/XGB_model.sav'
joblib.dump(model_xgboost,file_name)

['Trained Model/XGB_model.sav']

In [24]:
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6432349428425184


In [25]:
print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.38      0.44      2214
           1       0.68      0.81      0.74      3647

    accuracy                           0.64      5861
   macro avg       0.61      0.59      0.59      5861
weighted avg       0.63      0.64      0.63      5861



In [26]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, Y_pred))


Confusion Matrix:
[[ 831 1383]
 [ 708 2939]]


In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [28]:
model_svm = SVC(kernel='linear')

In [29]:
model_svm.fit(X_train, Y_train)

SVC(kernel='linear')

In [30]:
Y_pred = model_svm.predict(X_test)

In [55]:
file_name='Trained Model/SVM_model.sav'
joblib.dump(model_svm,file_name)

['Trained Model/SVM_model.sav']

In [32]:
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6543252004777341


In [33]:
print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.33      0.42      2214
           1       0.68      0.85      0.75      3647

    accuracy                           0.65      5861
   macro avg       0.63      0.59      0.59      5861
weighted avg       0.64      0.65      0.63      5861



In [34]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, Y_pred))


Confusion Matrix:
[[ 725 1489]
 [ 537 3110]]


In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score

from pylab import rcParams
rcParams['figure.figsize'] = 8, 8

In [36]:
classifier1 = RandomForestClassifier() 
grid_values = {'n_estimators':[10, 20], 'max_depth':[3, 5]}
classifier = GridSearchCV(classifier1, param_grid = grid_values, scoring = 'roc_auc', cv=5)

classifier.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [3, 5], 'n_estimators': [10, 20]},
             scoring='roc_auc')

In [37]:
train_preds =  classifier.predict(X_train)
test_preds  = classifier.predict(X_test)

In [54]:
file_name='Trained Model/RF_model.sav'
joblib.dump(classifier,file_name)

['Trained Model/RF_model.sav']

In [39]:
accuracy_score(Y_train,train_preds)

0.6839256984057335

In [40]:
accuracy_score(Y_test,test_preds)

0.6570551100494796

In [41]:
print("\nClassification Report:")
print(classification_report(Y_test, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.33      0.42      2214
           1       0.68      0.85      0.75      3647

    accuracy                           0.65      5861
   macro avg       0.63      0.59      0.59      5861
weighted avg       0.64      0.65      0.63      5861



In [42]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, Y_pred))


Confusion Matrix:
[[ 725 1489]
 [ 537 3110]]


In [44]:
pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e4/14/d795bb156f8cc10eb1dcfe1332b7dbb8405b634688980aa9be8f885cc888/tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.16.1 from https://files.pythonhosted.org/packages/e0/36/6278e4e7e69a90c00e0f82944d8f2713dd85a69d1add455d9e50446837ab/tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/41/f0/7e988a019bc54b2db

In [45]:
from numpy import loadtxt
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [46]:
model_nn = Sequential()
model_nn.add(Dense(6, input_dim=6, activation='relu'))
model_nn.add(Dense(12, activation='relu'))
model_nn.add(Dense(6, activation='relu'))
model_nn.add(Dense(1, activation='sigmoid'))

C:\Users\rahul\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [47]:
model_nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [48]:
model_nn.fit(X, Y, epochs=11, batch_size=5)

Epoch 1/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 11s 2ms/step - accuracy: 0.5684 - loss: 2.3533
Epoch 2/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6136 - loss: 0.7897
Epoch 3/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6125 - loss: 0.7476
Epoch 4/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6289 - loss: 0.6942
Epoch 5/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6291 - loss: 0.6938
Epoch 6/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6333 - loss: 0.6552
Epoch 7/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6439 - loss: 0.6406
Epoch 8/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6387 - loss: 0.6477
Epoch 9/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6409 - loss: 0.6284
Epoch 10/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6505 - loss: 0.6229
Epoch 11/11
3907/3907 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6389 - loss: 0.6255


In [50]:
model_nn.save('Trained Model/NN_model.h5')

In [51]:
import numpy as np
arr=np.array([[1067,4.434499033,4.109890158,2.596118485,77.35028763,77.04324442]])
pred=model_nn.predict(arr)
pred = pred*100
print(pred)
if pred>50:
    print("Needed")
else:
    print("Not Needed")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step
[[45.554825]]
Not Needed


In [52]:
import numpy as np
arr=np.array([[382,2.162553685,7.77492339,2.727348376,77.00087426,71.62384988]])

pred_logistic=model_logistic.predict(arr)
pred_logistic = pred_logistic*100

pred_xgboost=model_xgboost.predict(arr)
pred_xgboost = pred_xgboost*100

pred_svm=model_svm.predict(arr)
pred_svm = pred_svm*100

pred_nn=model_nn.predict(arr)
pred_nn = pred_nn*100

pred_rf= classifier.predict(arr)
pred_rf= pred_rf*100

print(pred_logistic)
if pred_logistic>50:
    print("Needed")
else:
    print("Not Needed")
    
print(pred_xgboost)
if pred_xgboost>50:
    print("Needed")
else:
    print("Not Needed")

print(pred_svm)
if pred_svm>50:
    print("Needed")
else:
    print("Not Needed")
    
print(pred_nn)
if pred_nn>50:
    print("Needed")
else:
    print("Not Needed")
    
print(pred_rf)
if pred_rf>50:
    print("Needed")
else:
    print("Not Needed")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[100]
Needed
[100]
Needed
[100]
Needed
[[83.37269]]
Needed
[100]
Needed


C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [53]:

result=0

if pred_logistic>50:
    result=result+1
    

if pred_xgboost>50:
    result=result+1



if pred_svm>50:
    result=result+1
    

if pred_nn>50:
    result=result+1
    

if pred_rf>50:
    result=result+1
    
print (result)
if result>2:
    print("Needed")
else:
    print("Not Needed")

5
Needed
