In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib
from tensorflow.keras.models import load_model

In [2]:
LR_model= joblib.load('Trained Model/LR_model.sav')
SVM_model= joblib.load('Trained Model/SVM_model.sav')
RF_model= joblib.load('Trained Model/RF_model.sav')
XGB_model= joblib.load('Trained Model/XGB_model.sav')
NN_model= load_model('Trained Model/NN_model.h5')

In [7]:
import numpy as np
arr=np.array([[382,2.162553685,7.77492339,2.727348376,77.00087426,71.62384988]])

pred_logistic=LR_model.predict(arr)

pred_xgboost=XGB_model.predict(arr)

pred_svm= SVM_model.predict(arr)

pred_nn=NN_model.predict(arr)

pred_rf= RF_model.predict(arr)

if pred_logistic>=1:
    print("Needed")
else:
    print("Not Needed")
    
if pred_xgboost>=1:
    print("Needed")
else:
    print("Not Needed")

if pred_svm>=1:
    print("Needed")
else:
    print("Not Needed")
    
if pred_nn>=0.5:
    print("Needed")
else:
    print("Not Needed")
    
if pred_rf>50:
    print("Needed")
else:
    print("Not Needed")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Needed
Needed
Needed
Needed
Not Needed


C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [8]:
data = pd.read_csv('engine_data.csv')

In [9]:
X = data.iloc[:,:-1]
X.head()

Engine rpm  Lub oil pressure  Fuel pressure  Coolant pressure  \
0         700          2.493592      11.790927          3.178981   
1         876          2.941606      16.193866          2.464504   
2         520          2.961746       6.553147          1.064347   
3         473          3.707835      19.510172          3.727455   
4         619          5.672919      15.738871          2.052251   

   lub oil temp  Coolant temp  
0     84.144163     81.632187  
1     77.640934     82.445724  
2     77.752266     79.645777  
3     74.129907     71.774629  
4     78.396989     87.000225

In [10]:
Y = data.iloc[:,-1] 
Y.head()

0    1
1    0
2    1
3    1
4    0
Name: Engine Condition, dtype: int64

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [12]:
pred_logistic=LR_model.predict(X_train)

In [13]:
pred_xgboost=XGB_model.predict(X_train)

In [14]:
pred_svm= SVM_model.predict(X_train)

In [15]:
pred_nn=NN_model.predict(X_train)

428/428 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [16]:
pred_rf= RF_model.predict(X_train)

In [17]:
print(pred_logistic)
print(pred_xgboost)
print(pred_svm)
print(pred_nn)
print(pred_rf)

[1 1 1 ... 1 0 1]
[0 1 1 ... 0 0 1]
[1 1 1 ... 1 0 1]
[[0.5416982 ]
 [0.8337269 ]
 [0.5661549 ]
 ...
 [0.65045726]
 [0.39815038]
 [0.6102017 ]]
[1 1 1 ... 1 0 1]


In [20]:
import csv
file_name="Manipulated Data/output_data.csv"
with open(file_name,'w',newline='') as csvfile:
    writer=csv.writer(csvfile)
    for row in zip(pred_nn,pred_xgboost,pred_svm,pred_logistic
                   ,pred_rf):
        writer.writerow(row)
    

In [21]:
import pandas as pd
outputdata = pd.read_csv('Manipulated Data/output_data.csv')
Y_pred = outputdata.iloc[:,-1]

In [22]:
Y_pred.head()

0    0
1    1
2    1
3    1
4    1
Name: i, dtype: int64

In [23]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(Y_train, Y_pred)

In [24]:
print("\nAccuracy:")
print(accuracy)


Accuracy:
0.7923796986982594


In [25]:
print("\nClassification Report:")
print(classification_report(Y_train, Y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.75      0.72      5004
           1       0.85      0.82      0.83      8670

    accuracy                           0.79     13674
   macro avg       0.78      0.78      0.78     13674
weighted avg       0.80      0.79      0.79     13674



In [26]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_train, Y_pred))


Confusion Matrix:
[[3742 1262]
 [1577 7093]]


In [27]:
import numpy as np
arr=np.array([[382,2.162553685,7.77492339,2.727348376,77.00087426,71.62384988]])

pred_logistic=LR_model.predict(arr)

pred_xgboost=XGB_model.predict(arr)

pred_svm= SVM_model.predict(arr)

pred_nn=NN_model.predict(arr)

pred_rf= RF_model.predict(arr)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\rahul\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [28]:
sum= pred_logistic+pred_xgboost+pred_svm+pred_nn+pred_rf
print(sum)

[[4.83372688]]


In [29]:
if(sum<4.3):
    print("Needed")
else:
    print(" not Needed")

 not Needed
